@startuml usecase

skinparam defaultFontName "Times New Roman"
skinparam linetype polyline
skinparam defaultFontSize 10

left to right direction

actor User

rectangle {

usecase "Melihat Dashboard\nMonitoring" as UC1

usecase "Pilih\nSemester" as UC2

usecase "Upload Data\nLMS (ZIP)" as UC3

usecase "Melihat Progress\nAktivitas" as UC6

usecase "Pilih\nAktivitas" as UC7

usecase "Cari\nAktivitas" as UC8

usecase "Melihat Detail\nAktivitas" as UC4

usecase "Pilih Mata\nKuliah" as UC5

usecase "Export Data\nMonitoring" as UC9

usecase "Download Data\nPer Mata Kuliah" as UC10

usecase "Download Semua\nData Semester" as UC11

}

User --> UC1
User --> UC4
User --> UC6
User --> UC9

' =========================
' DASHBOARD
' =========================

UC1 ..> UC2 : <<include>>
UC1 ..> UC3 : <<include>>

' =========================
' PROGRESS AKTIVITAS
' =========================

UC4 ..> UC5 : <<include>>

' =========================
' DETAIL AKTIVITAS
' =========================

UC6 ..> UC7 : <<include>>
UC6 ..> UC8 : <<include>>

' =========================
' EXPORT
' =========================

UC9 ..> UC10 : <<include>>
UC9 ..> UC11 : <<include>>

}

@enduml